name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        protocol: ftps
        server: ${{ secrets.FTP_ARI10_HOST }}
        username: ${{ secrets.FTP_ARI10_USER }}
        password: ${{ secrets.FTP_ARI10_PASSWORD }}