name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install lftp
        run: sudo apt install lftp 
      - name: Send files via ftp
        run: lftp 's153.cyber-folks.pl' -u 'ari10@citystudio.pl','15P-O.9[Vpu-Jd[+' -e "set ftp:ssl-force true; set ssl:verify-certificate false; mirror . --reverse --continue --dereference -x ^\.git/$ . .; quit"