name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    name: Deploy-Ari10-via-FTP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action
      env:
        FTP_SERVER: 's153.cyber-folks.pl'
        FTP_USERNAME: 'ari10@citystudio.pl'
        FTP_PASSWORD: '15P-O.9[Vpu-Jd[+'
        PORT: 21
        METHOD: sftp
        REMOTE_DIR: /home/cyberek/domains/citystudio.pl/public_html/ari10
        ARGS: --verbose