name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master
      - name: 📂 Sync files
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_ARI10_HOST }}
          user: ${{ secrets.FTP_ARI10_USER }}
          password: '15P-O.9[Vpu-Jd[+'
          forceSsl: true