name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install lftp
        run: sudo apt install lftp 
      # - name: Upload ftp
      #   uses: sebastianpopp/ftp-action@releases/v2
      #   with:
      #     host: "s153.cyber-folks.pl"
      #     user: "ari10@citystudio.pl"
      #     password: "15P-O.9[Vpu-Jd[+"
      #     localDir: "."
      #     remoteDir: "."