name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master
      - name: 📂 Sync files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: 's153.cyber-folks.pl'
          remote-user: 'cyberek'
          private-ssh-key: ${{ secrets.ARI10_SSH_KEY }}
          destination-path: ~/domains/citystudio.pl/public_html/ari10/
          ssh-port: 222