name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    name: 🎉 Deploy-Ari10-via-FTP
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@master
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: 's153.cyber-folks.pl'
          username: 'ari10@citystudio.pl'
          password: '15P-O.9[Vpu-Jd[+'
          port: 21
          protocol: ftps
          server-dir: /home/cyberek/domains/citystudio.pl/public_html/ari10/
          log-level: verbose