name: Deploy Ari10 via FTP
run-name: ${{ github.actor }} is deploying Ari10 via FTP 🚀
on:
  push:
    branches:
      - master
jobs:
  Deploy-Ari10-via-FTP:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Upload ftp
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_ARI10_HOST }}
          user: ${{ secrets.FTP_ARI10_USER }}
          password: ${{ secrets.FTP_ARI10_PASSWORD }}
          localDir: ""
          remoteDir: ""
          options: "--delete --asci"